### ISSUE TITLE
psql: FATAL:  role "koji" does not exist

### ISSUE THREAD

**Issue by laapsaap** [kostyrevaa/ansible-koji-db#1]
If I run this with the other roles on a new vm, I get this;
psql: FATAL:  role "koji" does not exist

**Comment by kostyrev** [comment]
did you read the reqs?
"This role doesn't not provision PostgreSQL setup nor does it creates postgresql users for you"

**Comment by kostyrev** [comment]
also please provide ansible's output of failed task

**Comment by laapsaap** [comment]
Yes I see your reqs now :) I got it working, somehow I expected koji-db using patrik.uytterhoeven.PostgreSQL-For-RHEL6x for the creation.  

btw great playbook for koji, save me much time.

**Comment by kostyrev** [comment]
> btw great playbook for koji, save me much time.

that was the whole point in writing it.

P.S. so if everything is fine close the issue

**Comment by kostyrev** [comment]
btw the https://github.com/kostyrevaa/ansible-koji-db#example-playbook clearly shows how to use patrik.uytterhoeven.PostgreSQL-For-RHEL6x
